site_title: "Hagit Harmon - IFS Therapist & Zen Meditation Teacher"
site_description: "Internal Family Systems therapy and Zen Buddhist meditation practice in Tel Aviv"

contact:
  email: "contact@hagitharmon.com"
  phone: ""
  instagram: "#"
  facebook: "#"
